import type { MetadataRoute } from 'next';

/**
 * GET /robots.txt — generated by Next.js App Router.
 *
 * Allow indexowanie marketingowych stron (homepage, /privacy-policy).
 * Disallow publiczne oferty (`/o/[token]`) i admin/auth — nie chcemy ich w
 * Google. Tokeny ofert sa unguessable (24 bytes base64), ale prewencyjnie.
 */
export default function robots(): MetadataRoute.Robots {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? 'https://oferta.k2biznes.pl';
  return {
    rules: [
      {
        userAgent: '*',
        allow: ['/', '/privacy-policy'],
        disallow: ['/o/', '/admin/', '/auth/', '/api/'],
      },
    ],
    host: base,
  };
}
